export default {
  message: {
    YES: 'Sim',
    NO: 'Não',
    ON_CANCEL: 'Deseja realmente voltar?',
    ON_POST: 'Deseja realmente cadastrar? verifique se todos os campos foi preenchido.',
    ON_DELETE: 'Deseja realmente excluir o item selecionado?',
    ON_DELETES: 'Deseja realmente excluir os itens selecionados?',
    REQUIRED_IVALID: "Campos com '*' são obrigatórios.",
    SUGGESTION_INVALID_VALUE: 'Selecione um valor válido da caixa de sugestões',
    HORA_INVALID: 'As horas devem estar entre {0} e {1}',
    EMAIL_INVALID: 'Insira um email válido',
    MIN_LENGTH_INVALID: value => `O valor mínimo aceito são ${value} caracteres.`,
    MAX_LENGTH_INVALID: value => `O valor máximo aceito são ${value} caracteres.`,
    MIN_INVALID: value => `O valor deve ser maior que ${value}.`,
    MAX_INVALID: value => `O valor deve ser menor que ${value}.`,
    CPF_INVALID: 'CPF inválido.',
    CNPJ_INVALID: 'CNPJ inválido.',
    EXTENSION_FILE_INVALID: 'Formato de arquivo inválido.',
    TELEFONE_INVALID: 'Telefone inválido.',
    MAX_LENGTH_NAME_FILE: value => `O Nome do Arquivo aceita somente até ${value} caracteres.`,
    MAX_VALOR: value => `O valor máximo aceito é ${value}.`,
    MIN_VALOR: value => `O valor mínimo aceito é ${value}.`,
  },
};
